backend:
  name: git-gateway

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "about" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "About" # Used in the UI, ie.: "New Post"
    folder: "site/content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it }
      - {label: "Title", name: "title", widget: "string", default: "About" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text", default: "Summary"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "price" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Price" # Used in the UI, ie.: "New Post"
    folder: "site/content/price" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it }
      - {label: "Order", name: "weight", widget: number, default: 999 }
      - {label: "Title", name: "title", widget: "string", default: "About" }
      - {label: "Price", name: "price", widget: "string", default "â‚¬10.00 + P&P" }
      - {label: "Summary", name: "description", widget: "text", default: "Summary"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Call to action", name: "cta", widget: "markdown", default: "[Enquire](mailto:francesca.tomassini@gmail.com?subject=Website,%20500g%20enquiry.&body=Please%20tell%20me%20how%20much%20it%20is%20to%20post%20to%20my%20address%3A%0D%0A%0D%0A%0D%0APostcode%3A%0D%0A%0D%0A%0D%0A%0D%0A%20Thank%20you%0D%0A%0D%0A%0D%0A%0D%0A)"}
      # {label: "Body", name: "body", widget: "markdown"}


  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it }
      - {label: "Title", name: "title", widget: "string", default: "New Post" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text", default: "Summary"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}


      - file: "site/content/banner/_index.md"
        label: "Banner"
        name: "banner"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: it}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Banner
            name: banner
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}

# bringing together sections and partials
      - file: "site/content/aggregate/_index.md"
        label: "aggregate Page"
        name: "aggregate"
        fields:
          - {label: 'Region', name: 'region', widget: 'select', options: ['en', 'it'], required: true, default: en}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: aggregate
            name: aggregate
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}

          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
